# Generated by Django 2.2.24 on 2024-11-11 13:41

from django.db import migrations
import phonenumbers


def copy_owners_phonenumber_to_owner_pure_phone(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    for flat in flat_model.objects.all():
        owners_phonenumber = flat.owners_phonenumber
        try:
            owner_pure_phone = phonenumbers.parse(owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(owner_pure_phone):
                flat.owner_pure_phone = owner_pure_phone
                flat.save()
        except:
            pass


def move_backward(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    for flat in flat_model.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20241009_0654'),
    ]

    operations = [
        migrations.RunPython(
            copy_owners_phonenumber_to_owner_pure_phone,
            move_backward
        )
    ]
