# Generated by Django 2.2.24 on 2024-11-12 15:34

from django.db import migrations


def copy_from_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    OwnerModel = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        OwnerModel.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20241112_2013'),
    ]

    operations = [
        migrations.RunPython(copy_from_flat_to_owner, move_backward)
    ]
