# Generated by Django 2.2.24 on 2024-11-13 01:53

from django.db import migrations


def link_flats_to_owner(apps, schemaeditor):
    FlatModel = apps.get_model('property', 'Flat')
    OwnerModel = apps.get_model('property', 'Owner')

    for flat in FlatModel.objects.iterator():
        owner = OwnerModel.objects.filter(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        ).first()
        if owner:
            flat.owners.add(owner)
            flat.save()


def move_backward(apps, schema_editor):
    FlatModel = apps.get_model('property', 'Flat')
    for flat in FlatModel.objects.all():
        flat.owners.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20241112_2034'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owner, move_backward)
    ]
